
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from .config import SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD
from .models import AnalysisReport

async def send_email_report(report: AnalysisReport):
    """
    Send the analysis report via email
    """
    if not SMTP_USER or not SMTP_PASSWORD:
        print("Error: SMTP credentials not set. Skipping email.")
        return

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"Your AI Product Discovery Report: {report.keywords}"
        msg["From"] = SMTP_USER
        msg["To"] = report.user_email

        # Create the body of the message (a plain-text and an HTML version)
        # We'll use the report_html if available, otherwise markdown wrapped in pre
        if report.report_html:
            html_content = f"""
            <html>
                <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
                    <div style="max-width: 800px; margin: 0 auto; padding: 20px;">
                        <h2 style="color: #2563eb;">Product Discovery Analysis Complete</h2>
                        <p>Here is the analysis report for <strong>{report.keywords}</strong> in <strong>{report.category}</strong>.</p>
                        <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
                        {report.report_html}
                        <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
                        <p style="font-size: 12px; color: #666;">Generated by Amz AI Agent</p>
                    </div>
                </body>
            </html>
            """
        else:
             html_content = f"""
            <html>
                <body>
                    <h2>Analysis Report</h2>
                    <pre>{report.report_markdown}</pre>
                </body>
            </html>
            """

        part = MIMEText(html_content, "html")
        msg.attach(part)

        # Connect to server
        print(f"Connecting to SMTP server {SMTP_HOST}:{SMTP_PORT}...")
        server = smtplib.SMTP(SMTP_HOST, SMTP_PORT)
        server.starttls()  # Secure the connection
        server.login(SMTP_USER, SMTP_PASSWORD)
        
        # Send email
        server.sendmail(SMTP_USER, report.user_email, msg.as_string())
        server.quit()
        
        print(f"✅ Email sent successfully to {report.user_email}")
        
    except Exception as e:
        print(f"❌ Failed to send email: {str(e)}")
        # Don't raise, just log error so main process continues
